"""add_fields_for_jobs

Revision ID: 8f1557cb0645
Revises: 23dbd14b9b59
Create Date: 2025-02-04 18:04:34.365386

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f638fce04851"
down_revision: Union[str, None] = "23dbd14b9b59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job", sa.Column("deadline", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "job",
        sa.Column(
            "is_completed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column("job", sa.Column("author_id", sa.Integer(), nullable=False))
    op.add_column(
        "job", sa.Column("performer_id", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "job",
        "is_archived",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_job_author_id"), "job", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_performer_id"), "job", ["performer_id"], unique=False
    )
    op.create_foreign_key(
        None, "job", "user", ["author_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "job", "user", ["performer_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "job", type_="foreignkey")
    op.drop_constraint(None, "job", type_="foreignkey")
    op.drop_index(op.f("ix_job_performer_id"), table_name="job")
    op.drop_index(op.f("ix_job_author_id"), table_name="job")
    op.alter_column(
        "job",
        "is_archived",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_column("job", "performer_id")
    op.drop_column("job", "author_id")
    op.drop_column("job", "is_completed")
    op.drop_column("job", "deadline")
    # ### end Alembic commands ###
